name: stepin
services:
  stepin:
    image: allape/stepin
#    build: docker build --build-arg https_proxy=http://host.docker.internal:1080 -t allape/stepin .
    volumes:
      - ./stepin-config:/etc/stepin
      - ./templates:/app/templates
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - STEPIN_BIND=
      - STEPIN_ALLOWED_IP=127.0.0.1,172.19.0.1,172.20.0.1
      - STEPIN_ROOT_CA_PASSWORD=
        STEPIN_INTERMEDIA_CA_PASSWORD=
