name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - /docker.compose.yaml
      - /README.md
      - /examples

jobs:

  build:

    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: "docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:main-${{ github.sha }}"

      - name: Log in to GitHub Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image
        run: "docker push ghcr.io/${{ github.repository }}:main-${{ github.sha }}"

      - name: Tag the Docker image as main
        run: "docker tag ghcr.io/${{ github.repository }}:main-${{ github.sha }} ghcr.io/${{ github.repository }}:main && docker push ghcr.io/${{ github.repository }}:main"
